[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tic_tac_toe = "8yKkFNF7AmQivwb7NmLY3granCvv9dujhmTaz7nRA57p"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = 'C:\Users\chera\.config/solana/id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
